# Generated by Django 2.2.18 on 2021-03-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
    ]
